{
    TFile::Open("outBATHist.root");
    cout << "cts/(keV•kg•yr)\n";
    double tot = BIcalc(hsumBEGe, 20.46) + BIcalc(hsumCOAX, 16.22);
    double sum = tot;
    cout << "\tTotal: " << tot << endl;
    tot = BIcalc(hDataBEGe, 20.46)                  + BIcalc(hDataCOAX, 16.22);
    cout << "\tTotal: " << tot << endl; sum += tot;
    tot = BIcalc(h2nbbBEGe, 20.46)                  + BIcalc(h2nbbCOAX, 16.22);
    cout << "\tTotal: " << tot << endl; sum += tot;
    tot = BIcalc(h2nbbLVBEGe, 20.46)                + BIcalc(h2nbbLVCOAX, 16.22);
    cout << "\tTotal: " << tot << endl; sum += tot;
    tot = BIcalc(hK42homLArBEGe, 20.46)             + BIcalc(hK42homLArCOAX, 16.22);
    cout << "\tTotal: " << tot << endl; sum += tot;
    tot = BIcalc(hK40fibersBEGe, 20.46)             + BIcalc(hK40fibersCOAX, 16.22);
    cout << "\tTotal: " << tot << endl; sum += tot;
    tot = BIcalc(hBi212fibersBEGe, 20.46)           + BIcalc(hBi212fibersCOAX, 16.22);
    cout << "\tTotal: " << tot << endl; sum += tot;
    tot = BIcalc(hTl208fibersBEGe, 20.46)           + BIcalc(hTl208fibersCOAX, 16.22);
    cout << "\tTotal: " << tot << endl; sum += tot;
    tot = BIcalc(hPb214fibersBEGe, 20.46)           + BIcalc(hPb214fibersCOAX, 16.22);
    cout << "\tTotal: " << tot << endl; sum += tot;
    tot = BIcalc(hBi214fibersBEGe, 20.46)           + BIcalc(hBi214fibersCOAX, 16.22);
    cout << "\tTotal: " << tot << endl; sum += tot;
    tot = BIcalc(hAlphaBEGe, 20.46)                 + BIcalc(hAlphaCOAX, 16.22);
    cout << "\tTotal: " << tot << endl; sum += tot;
    tot = BIcalc(hK42nPlusBEGe, 20.46)              + BIcalc(hK42nPlusCOAX, 16.22);
    cout << "\tTotal: " << tot << endl; sum += tot;
    tot = BIcalc(hK42pPlusBEGe, 20.46)              + BIcalc(hK42pPlusCOAX, 16.22);
    cout << "\tTotal: " << tot << endl; sum += tot;
    tot = BIcalc(hAc228holderBEGe, 20.46)           + BIcalc(hAc228holderCOAX, 16.22);
    cout << "\tTotal: " << tot << endl; sum += tot;
    tot = BIcalc(hCo60holderBEGe, 20.46)            + BIcalc(hCo60holderCOAX, 16.22);
    cout << "\tTotal: " << tot << endl; sum += tot;
    tot = BIcalc(hK40holderBEGe, 20.46)             + BIcalc(hK40holderCOAX, 16.22);
    cout << "\tTotal: " << tot << endl; sum += tot;
    tot = BIcalc(hBi212holderBEGe, 20.46)           + BIcalc(hBi212holderCOAX, 16.22);
    cout << "\tTotal: " << tot << endl; sum += tot;
    tot = BIcalc(hTl208holderBEGe, 20.46)           + BIcalc(hTl208holderCOAX, 16.22);
    cout << "\tTotal: " << tot << endl; sum += tot;
    tot = BIcalc(hPb214holderBEGe, 20.46)           + BIcalc(hPb214holderCOAX, 16.22);
    cout << "\tTotal: " << tot << endl; sum += tot;
    tot = BIcalc(hBi214holderBEGe, 20.46)           + BIcalc(hBi214holderCOAX, 16.22);
    cout << "\tTotal: " << tot << endl; sum += tot;
    tot = BIcalc(hK40cablesBEGe, 20.46)             + BIcalc(hK40cablesCOAX, 16.22);
    cout << "\tTotal: " << tot << endl; sum += tot;
    tot = BIcalc(hBi212cablesBEGe, 20.46)           + BIcalc(hBi212cablesCOAX, 16.22);
    cout << "\tTotal: " << tot << endl; sum += tot;
    tot = BIcalc(hTl208cablesBEGe, 20.46)           + BIcalc(hTl208cablesCOAX, 16.22);
    cout << "\tTotal: " << tot << endl; sum += tot;
    tot = BIcalc(hPb214cablesBEGe, 20.46)           + BIcalc(hPb214cablesCOAX, 16.22);
    cout << "\tTotal: " << tot << endl; sum += tot;
    tot = BIcalc(hBi214cablesBEGe, 20.46)           + BIcalc(hBi214cablesCOAX, 16.22);
    cout << "\tTotal: " << tot << endl; sum += tot;
    tot = BIcalc(hK40minishroudBEGe, 20.46)         + BIcalc(hK40minishroudCOAX, 16.22);
    cout << "\tTotal: " << tot << endl; sum += tot;
    tot = BIcalc(hPa234minishroudBEGe, 20.46)       + BIcalc(hPa234minishroudCOAX, 16.22);
    cout << "\tTotal: " << tot << endl; sum += tot;
    tot = BIcalc(hBi207minishroudBEGe, 20.46)       + BIcalc(hBi207minishroudCOAX, 16.22);
    cout << "\tTotal: " << tot << endl; sum += tot;
    tot = BIcalc(hBi207cablesBEGe, 20.46)           + BIcalc(hBi207cablesCOAX, 16.22);
    cout << "\tTotal: " << tot << endl; sum += tot;
    tot = BIcalc(hBi207holderBEGe, 20.46)           + BIcalc(hBi207holderCOAX, 16.22);
    cout << "\tTotal: " << tot << endl; sum += tot;
    tot = BIcalc(hPb214minishroudBEGe, 20.46)       + BIcalc(hPb214minishroudCOAX, 16.22);
    cout << "\tTotal: " << tot << endl; sum += tot;
    tot = BIcalc(hBi214minishroudBEGe, 20.46)       + BIcalc(hBi214minishroudCOAX, 16.22);
    cout << "\tTotal: " << tot << endl; sum += tot;
    tot = BIcalc(K42minishroudsurfaceBEGe, 20.46)   + BIcalc(K42minishroudsurfaceCOAX, 16.22);
    cout << "\tTotal: " << tot << endl; sum += tot;
    tot = BIcalc(Pa234cablesBEGe, 20.46)            + BIcalc(Pa234cablesCOAX, 16.22);
    cout << "\tTotal: " << tot << endl; sum += tot;
    tot = BIcalc(Pa234holderBEGe, 20.46)            + BIcalc(Pa234holderCOAX, 16.22);
    cout << "\tTotal: " << tot << endl; sum += tot;
    tot = BIcalc(K42homLArAABEGe, 20.46)            + BIcalc(K42homLArAACOAX, 16.22);
    cout << "\tTotal: " << tot << endl; sum += tot;
    cout << "Sum: " << sum << endl;
    gApplication->Terminate();
}
double BIcalc( TH1* h, double exposure ) {
    int low_range = h->GetXaxis()->FindBin(570);
    int up_range =h->GetXaxis()->FindBin(5300);

    int low = h->GetXaxis()->FindBin(1930);
    int up  = h->GetXaxis()->FindBin(2190);
    int bli_low = h->GetXaxis()->FindBin(2014);
    int bli_up = h->GetXaxis()->FindBin(2064);
    int tl_low = h->GetXaxis()->FindBin(2099);
    int tl_up = h->GetXaxis()->FindBin(2109);
    int bi_low = h->GetXaxis()->FindBin(2114);
    int bi_up = h->GetXaxis()->FindBin(2124);
    double intg = h->Integral(low, up) - h->Integral(bli_low, bli_up) - h->Integral(tl_low, tl_up) - h->Integral(bi_low, bi_up);
    //cout << "Counts: " << intg << endl;
    int nbins = (up-low+1) - (bli_up-bli_low+1) - (tl_up-tl_low+1) - (bi_up-bi_low+1);
    //cout << "range: " << nbins*4 << " keV\n";
    cout << setw(25) << left << h->GetName() << "total cts: " << setw(10) << left << h->Integral(low_range, up_range) << " BI: " << intg/(exposure*nbins*4) << endl;
    return intg/(exposure*nbins*4);
}
